name: HyperV
on:
  push:
    branches:
    - master
    paths:
    - .github/workflows/hyperv.yml
    - actions/packer-hyperv/Dockerfile
    - hyperv.json

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: hyperv - packer build
        run: |
          choco install -y packer
          Enable-WindowsOptionalFeature -Online -FeatureName  Microsoft-Hyper-V-Tools-All
          packer build hyperv.json