name: Packer
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: packer validate
        uses: docker://hashicorp/packer:1.4.3
        with:
          args: validate packer.json
      - name: packer build
        uses: docker://hashicorp/packer:1.4.3
        with:
          args: build packer.json