name: Packer
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: packer validate packer.json
        uses: docker://hashicorp/packer:1.4.3
        with:
          args: validate packer.json