name: Virtualbox
on:
  push:
    branches:
    - master
    paths:
    - .github/workflows/virtualbox.yml
    - actions/packer-virtualbox/Dockerfile
    - virtualbox.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: virtualbox - packer validate
        uses: docker://hashicorp/packer:1.4.3
        with:
          args: validate virtualbox.json
      - name: virtualbox - packer build
        uses: ./actions/packer-virtualbox
        with:
          args: build virtualbox.json